export const projects = [
    {
        slug: "catering-management-system",
        title: "AI-Powered Catering Management System",
        description: "Full-stack catering platform with AI workflows.",
        longDescription:
            "Built a full-stack production system processing 500+ daily transactions. Implemented async workflows with Celery and Redis for order processing and notifications. Integrated Square POS and WhatsApp Business APIs.",
        tech: ["Python", "Django", "React", "PostgreSQL", "Redis", "AWS", "Celery"],
        image: "/projects/catering.png",
        github: "https://github.com/sumanthvarma27/catering-order-assistant",
        demo: "#",
        metrics: "500+ daily transactions",
        features: [
            "Order processing with Celery/Redis",
            "Square POS integration",
            "WhatsApp Business API notifications",
            "99.8% uptime on AWS",
        ],
        date: "2025-02-01",
    },
    {
        slug: "docuvault",
        title: "DocuVault - Document Management",
        description: "Secure document management with role-based access.",
        longDescription:
            "Engineered a full-stack application serving 1,000+ users. Designed PostgreSQL schema for metadata and full-text search. Implemented RBAC and deployed on AWS using Terraform.",
        tech: ["Python", "Django", "React", "PostgreSQL", "Terraform", "Jenkins"],
        image: "/projects/docuvault.png",
        github: "https://github.com/sumanthvarma27/docuvault",
        demo: "#",
        metrics: "1,000+ users served",
        features: [
            "Role-Based Access Control (RBAC)",
            "Full-text search",
            "CI/CD with Jenkins",
            "AWS deployment via Terraform",
        ],
        date: "2025-01-15",
    },
    {
        slug: "logo-detection-tool",
        title: "Logo Detection Tool",
        description: "Computer vision system achieving 98%+ accuracy.",
        longDescription:
            "Built a vision system using YOLOv5 and OpenCV. Optimized inference pipeline reducing latency from 250ms to 85ms. Created an analytics dashboard for detection metrics.",
        tech: ["Python", "YOLOv5", "Flask", "React", "OpenCV", "Redis"],
        image: "/projects/logo-detection.png",
        github: "https://github.com/sumanthvarma27",
        demo: "#",
        metrics: "98% accuracy, 85ms latency",
        features: [
            "Real-time inference",
            "Batch processing with Celery",
            "Analytics dashboard",
            "90% code coverage",
        ],
        date: "2025-03-01",
    },
    {
        slug: "real-time-analytics",
        title: "Real-Time Analytics Platform",
        description: "Data analytics platform processing 1M+ records.",
        longDescription:
            "Developed a full-stack platform with Kafka data pipelines processing 1M+ daily records. Optimized PostgreSQL queries reducing report time by 60%. Monitoried with Datadog/Grafana.",
        tech: ["Python", "Django", "React", "Kafka", "Docker", "AWS"],
        image: "/projects/analytics.png",
        github: "https://github.com/sumanthvarma27",
        demo: "#",
        metrics: "1M+ records/day",
        features: [
            "Kafka data pipelines",
            "Docker containerization",
            "Datadog & Grafana monitoring",
            "Query optimization",
        ],
        date: "2024-11-01",
    },
    {
        slug: "job-hunter",
        title: "Job Hunter - AI Application Assistant",
        description: "Automated job tracking and application management tool.",
        longDescription:
            "An intelligent agent designed to streamline the job application process. Features automated status tracking, resume customization suggestions, and application management dashboard.",
        tech: ["Python", "React", "OpenAI API", "PostgreSQL"],
        image: "/projects/job-hunter.png",
        github: "https://github.com/sumanthvarma27/job-hunter",
        demo: "#",
        metrics: "Automated tracking workflow",
        features: [
            "Application status tracking",
            "Resume version control",
            "Automated follow-up reminders",
            "Analytics dashboard",
        ],
        date: "2025-04-01",
    },
    {
        slug: "rag-document-assistant",
        title: "RAG-Powered Document Assistant",
        description: "Retrieval-Augmented Generation system for grounded LLM responses.",
        longDescription:
            "Built Retrieval-Augmented Generation system grounding LLM responses in factual data, reducing hallucinations by 35%. Implemented semantic search using embeddings and vector database, processing 10K+ documents with 90% retrieval accuracy. Deployed RESTful API endpoints with Flask for connecting AI model to web application interface.",
        tech: ["Python", "LangChain", "Vector Database", "Flask", "OpenAI API"],
        image: "/projects/rag-assistant.png",
        github: "#",
        demo: "#",
        metrics: "35% fewer hallucinations, 90% retrieval accuracy",
        features: [
            "Semantic search with embeddings",
            "10K+ document processing",
            "RESTful API endpoints",
            "Vector database integration",
        ],
        date: "2024-08-01",
    },
    {
        slug: "ai-chatbot-member-services",
        title: "AI Chatbot for Member Services",
        description: "Conversational AI agent with 85% resolution rate.",
        longDescription:
            "Developed conversational AI agent using prompt engineering techniques to handle customer inquiries with 85% resolution rate. Integrated NLP capabilities for intent recognition and entity extraction using tokenization and transformer models. Built React frontend and Node.js backend with API integration for seamless user experience.",
        tech: ["Python", "Azure AI", "React", "Node.js", "NLP"],
        image: "/projects/ai-chatbot.png",
        github: "#",
        demo: "#",
        metrics: "85% resolution rate",
        features: [
            "Prompt engineering techniques",
            "Intent recognition & entity extraction",
            "Transformer-based NLP models",
            "React + Node.js full-stack",
        ],
        date: "2024-06-01",
    },
    {
        slug: "fraud-detection-pipeline",
        title: "Fraud Detection ML Pipeline",
        description: "ML pipeline processing 500K+ daily transactions.",
        longDescription:
            "Created data pipeline for structured and unstructured data ingestion processing 500K+ transactions daily. Implemented model governance with bias detection, transparency measures, and compliance documentation. Deployed with CI/CD using Docker and Git, following Agile sprints for iterative development.",
        tech: ["Python", "Databricks", "PostgreSQL", "Docker", "Git"],
        image: "/projects/fraud-detection.png",
        github: "#",
        demo: "#",
        metrics: "500K+ daily transactions",
        features: [
            "Structured & unstructured data ingestion",
            "Model governance & bias detection",
            "CI/CD with Docker",
            "Agile development workflow",
        ],
        date: "2024-04-01",
    },
]
